language: generic
sudo: required
services:
  - docker # install ready-to-go docker-cli in travis env

before_install: # do initial command
  - docker build -t barryblando/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true barryblando/docker-react npm run test -- --coverage