version: "3.8"
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app # map the current folder to the folder inside the container
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true # prevent from exiting code 0 cause of webpack dev server